name: CI 

on:

  pull_request:
    branches: [ "master" ]

jobs:
  run-test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup JDK 11 with cache Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
            
      
    - name: Maven test
      run: mvn clean test 
      env:
          CHROME_OPTIONS: --disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless;--window-size=1920,1080
          APP_OPTIONS: port=8080;admin.username=${{ secrets.ADMIN_USER }};admin.password=${{ secrets.ADMIN_PAS }}
          CI_RUN: true
      continue-on-error: true
      
    #- name: Check on failures
    #  if: steps.test.outcome != 'success'
    #  run: exit 1
